"""Provider-neutral contracts for GhostGUI's bounded AI editing workflow."""

from application.ai.errors import (
    AIError,
    ProviderCancelledError,
    ProviderAuthenticationError,
    ProviderCapabilityError,
    ProviderConfigurationError,
    ProviderError,
    ProviderRateLimitError,
    ProviderResponseError,
    ToolExecutionError,
    ToolNotFoundError,
    ToolRegistrationError,
    ToolValidationError,
)
from application.ai.schemas import (
    EditAuthor,
    ImageVariant,
    MessageRole,
    MotionEntityRef,
    MotionFrameImage,
    ProviderCapabilities,
    ProviderMessage,
    ProviderRequest,
    ProviderResponse,
    StopReason,
    ToolCall,
    ToolDefinition,
    ToolResult,
    Usage,
)
from application.ai.tool_registry import ToolCategory, ToolRegistry, ToolSpec
from application.ai.providers import GeminiProvider, LLMProvider, MockProvider, MockStep
from application.ai.edit_session import (
    AIEditSession,
    AIEditSessionError,
    AIEditSessionState,
    SessionEditRecord,
)
from application.ai.metadata import (
    InMemoryMotionMetadataStore,
    MotionEditMetadata,
    MotionMetadataService,
    TimestampMotionIdentityResolver,
)
from application.ai.motion_state import MotionStateSnapshot, ReplaceMotionState
from application.ai.preview import sample_working_preview_qpos
from application.ai.context import (
    AIContext,
    ContextBuilder,
    EditorSelectionContext,
    RobotCapabilityContext,
)
from application.ai.motion_services import (
    GhostGUIMotionService,
    LogicalFrameSolveResult,
    MotionValidationReport,
    SemanticMotionError,
)
from application.ai.semantic_tools import (
    SemanticToolContext,
    build_semantic_tool_registry,
)
from application.ai.agent import (
    AgentError,
    AgentLimitError,
    AgentLimits,
    AgentRunResult,
    AgentTimeoutError,
    AgentValidationError,
    GhostGUIAgent,
    ToolExecutionRecord,
)

__all__ = [
    "AIError",
    "AgentError",
    "AgentLimitError",
    "AgentLimits",
    "AgentRunResult",
    "AgentTimeoutError",
    "AgentValidationError",
    "AIEditSession",
    "AIEditSessionError",
    "AIEditSessionState",
    "AIContext",
    "ContextBuilder",
    "EditAuthor",
    "EditorSelectionContext",
    "GhostGUIMotionService",
    "GhostGUIAgent",
    "ImageVariant",
    "InMemoryMotionMetadataStore",
    "MessageRole",
    "LLMProvider",
    "GeminiProvider",
    "LogicalFrameSolveResult",
    "MockProvider",
    "MockStep",
    "MotionEditMetadata",
    "MotionEntityRef",
    "MotionFrameImage",
    "MotionMetadataService",
    "MotionStateSnapshot",
    "MotionValidationReport",
    "ProviderCancelledError",
    "ProviderAuthenticationError",
    "ProviderCapabilityError",
    "ProviderConfigurationError",
    "ProviderCapabilities",
    "ProviderError",
    "ProviderRateLimitError",
    "ProviderResponseError",
    "ProviderMessage",
    "ProviderRequest",
    "ProviderResponse",
    "ReplaceMotionState",
    "RobotCapabilityContext",
    "SemanticMotionError",
    "SemanticToolContext",
    "SessionEditRecord",
    "StopReason",
    "ToolCall",
    "ToolCategory",
    "ToolDefinition",
    "ToolExecutionError",
    "ToolExecutionRecord",
    "ToolNotFoundError",
    "ToolRegistrationError",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "ToolValidationError",
    "TimestampMotionIdentityResolver",
    "Usage",
    "build_semantic_tool_registry",
    "sample_working_preview_qpos",
]
