"""Shared local budgets for optional AI requests and responses."""

DEFAULT_MAX_OUTPUT_TOKENS = 4096
MAX_AI_OUTPUT_TOKENS = 16_384
MAX_AI_INSTRUCTION_CHARACTERS = 16_000
MAX_AI_RESPONSE_CHARACTERS = 65_536
MAX_TOOL_RESULT_CHARACTERS = 65_536
MAX_MOTION_FRAME_BYTES = 8 * 1024 * 1024

# Compact Motion Assistant request budgets. These are deliberately separate
# from the legacy semantic agent loop.
MAX_MOTION_CONTEXT_CHARACTERS = 120_000
MAX_MOTION_NUMERICAL_SAMPLES = 20
MAX_MOTION_IMAGES = 8
MAX_MOTION_IMAGE_DIMENSION = 512
DEFAULT_MOTION_REQUEST_TIMEOUT_SECONDS = 90.0
MAX_MOTION_REQUEST_TIMEOUT_SECONDS = 180.0
