#!/usr/bin/env python3
"""Validate that a built GhostGUI wheel contains its runtime contracts."""

from __future__ import annotations

import argparse
import configparser
import io
from pathlib import Path, PurePosixPath
import sys
import zipfile


REQUIRED_MODULES = frozenset(
    {
        "application/launcher.py",
        "application/render_diagnostics.py",
        "application/mujoco_viewer_process.py",
        "application/background_jobs.py",
        "application/history.py",
        "application/project_manager.py",
        "application/visualization/manager.py",
        "core/models/registry.py",
        "core/resources.py",
        "core/trajectory/model.py",
        "gui/main_window.py",
        "gui/panels/status_panel.py",
        "gui/theme.py",
        "gui/viewers/camera.py",
        "gui/viewers/opengl_compat.py",
        "gui/viewers/robot_canvas_3d.py",
    }
)
REQUIRED_METADATA_SUFFIXES = frozenset(
    {
        ".dist-info/METADATA",
        ".dist-info/WHEEL",
        ".dist-info/RECORD",
        ".dist-info/entry_points.txt",
    }
)
REQUIRED_RESOURCE_SUFFIXES = frozenset(
    {
        "share/ghostgui/docs/user_guide.md",
        "share/ghostgui/gui/assets/app/ghostlogo.svg",
        "share/ghostgui/gui/assets/theme/play-dark.svg",
        "share/ghostgui/models/g1_29dof.xml",
        "share/ghostgui/models/go2_description.urdf",
        "share/ghostgui/models/h2.urdf",
        "share/ghostgui/models/z1.urdf",
    }
)


def validate_wheel(
    wheel_path: Path,
    *,
    require_resources: bool = False,
) -> list[str]:
    wheel_path = Path(wheel_path)
    try:
        with zipfile.ZipFile(wheel_path) as archive:
            names = set(archive.namelist())
            entry_point_names = [
                name
                for name in names
                if name.endswith(".dist-info/entry_points.txt")
            ]
            entry_point_payloads = [
                archive.read(name).decode("utf-8", errors="replace")
                for name in entry_point_names
            ]
    except (OSError, zipfile.BadZipFile) as exc:
        return [f"cannot read wheel {wheel_path}: {exc}"]

    errors = []
    missing_modules = sorted(REQUIRED_MODULES - names)
    if missing_modules:
        errors.append(
            "missing Python runtime modules: " + ", ".join(missing_modules)
        )

    missing_metadata = sorted(
        suffix
        for suffix in REQUIRED_METADATA_SUFFIXES
        if not any(name.endswith(suffix) for name in names)
    )
    if missing_metadata:
        errors.append(
            "missing wheel metadata: " + ", ".join(missing_metadata)
        )
    else:
        entry_points = {}
        for payload in entry_point_payloads:
            parser = configparser.ConfigParser(interpolation=None)
            try:
                parser.read_file(io.StringIO(payload))
            except configparser.Error:
                errors.append("wheel entry-point metadata is malformed")
                continue
            for section in parser.sections():
                for name, value in parser.items(section):
                    entry_points[(section, name)] = value.strip()
        if entry_points.get(("console_scripts", "ghostgui")) != (
            "application.launcher:main"
        ):
            errors.append("ghostgui console entry point is missing or incorrect")
        if entry_points.get(("gui_scripts", "ghostgui-gui")) != (
            "application.launcher:main"
        ):
            errors.append("ghostgui GUI entry point is missing or incorrect")

    unsafe_members = sorted(
        name
        for name in names
        if (
            PurePosixPath(name).is_absolute()
            or ".." in PurePosixPath(name).parts
            or "\\" in name
        )
    )
    if unsafe_members:
        errors.append(
            "wheel contains unsafe member paths: " + ", ".join(unsafe_members)
        )

    generated_files = sorted(
        name
        for name in names
        if "__pycache__/" in name or name.endswith((".pyc", ".pyo"))
    )
    if generated_files:
        errors.append(
            "wheel contains generated bytecode: " + ", ".join(generated_files)
        )

    unwanted_files = sorted(
        name
        for name in names
        if name.startswith(("tests/", ".github/", ".git/"))
    )
    if unwanted_files:
        errors.append(
            "wheel contains repository-only files: "
            + ", ".join(unwanted_files)
        )

    if require_resources:
        missing_resources = sorted(
            suffix
            for suffix in REQUIRED_RESOURCE_SUFFIXES
            if not any(name.endswith(suffix) for name in names)
        )
        if missing_resources:
            errors.append(
                "missing bundled runtime resources: "
                + ", ".join(missing_resources)
            )
    return errors


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("wheel", type=Path)
    parser.add_argument(
        "--require-resources",
        action="store_true",
        help="also require bundled models, theme assets, and user documentation",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    errors = validate_wheel(
        args.wheel,
        require_resources=args.require_resources,
    )
    if errors:
        print("Wheel validation failed:")
        for error in errors:
            print(f"- {error}")
        return 1
    print(f"Wheel validation passed: {args.wheel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
